#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const foreach = require('foreach');
const server = require('../index.js')
const Mocha = require('mocha');
const mocha = new Mocha({
    ui: 'bdd',
    reporter: 'mochawesome',
    timeout: 6000,
    fullTrace:true
});

let tests = [
    path.join(__dirname, 'server.test.js')
]

foreach(tests, function(e, i, a){
    mocha.addFile(e);
})

// Run the tests after server starts
server(path.join(__dirname, '..', '.env')).then(function(suite){   
    mocha.run(function(failures){
	process.on('exit', function () {
	    suite.server.close(function(){
		suite.connection.close()
		process.exit(failures);  // exit with non-zero status if there were failures
	    })
	});
    })
});
